export const actionTypes = {
  CONNECT: 1,
  LOGIN_ACTION: 2,
  REGISTRATION_ACTION: 3,
  CALC_GOODS_ACTION: 4,
  CALC_AUTO_ACTION: 5,
  RETRIVEVE_USERS: 6,
  ADD_UNIT: 7,
  GET_UNITS: 8,
  GET_ALL_UNITS: 9,
  EDIT_USER: 10,
  BAN_USERS: 11,
  CLOSE_CONNECTION: -1,
};
export const executionResults = {
  SUCCESS: 0,
  INTERNAL_ERROR: 1,
};
